Clinica.create(nombre:'Centro de Obstetricia y Ginecología',telefono:'809-221-7100',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Centro de Otorrinolaringología y Especialidades',telefono:'809-682-0151',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Centro de Salud de la Mujer Atabey',telefono:'809-412-8177',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Alcántara y González',telefono:'809-566-2121',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Antillano',telefono:'809-533-4715',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Corominas Pepín',telefono:'809-541-1400',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM del Caribe',telefono:'809-685-9403',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Dominicano',telefono:'809-531-2800',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Dominico - Cubano',telefono:'809-221-5501',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Dr. Betances',telefono:'809-476-7373',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Dr. Escaño',telefono:'809-687-2090',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Dr. Richardson Cruz',telefono:'809-567-1471',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Gazcue',telefono:'809-412-7851',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Herrera',telefono:'809-537-3770',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Hispánico',telefono:'809-596-0033',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Integral II',telefono:'809-788-6336',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Integral Santana Guzmán',telefono:'809-788-1003',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Juan Carlos',telefono:'809-699-1111',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Luperón',telefono:'809-684-3989',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Panamericano',telefono:'809-538-5281',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Real',telefono:'809-537-3940',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Santos Aquino',telefono:'809-548-1002',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM UCE',telefono:'809-221-0171',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Centro Oriental de Ginecología y Obstetricia',telefono:'809-593-4386',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Centro Policlínico Nacional',telefono:'809-788-2323',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Centro Quirúrgico Esculapio',telefono:'809-682-6989',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Abreu',telefono:'809-688-4411',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Cruz Dorada',telefono:'809-689-5339',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Cruz Jiminian',telefono:'809-566-2271',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Dr. Abel González',telefono:'809-682-6001',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Dra. Evangelina Rodríguez (Pro-Familia II)',telefono:'809-684-3389',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Dr. Rosario',telefono:'809-681-3120',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Gómez Patiño',telefono:'809-685-9131',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Independencia',telefono:'809-533-2775',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Independencia Norte',telefono:'809-385-2787',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica La Altagracia',telefono:'809-699-3494',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Rodríguez Santos',telefono:'809-333-6671',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Tamares Espinal',telefono:'809-379-2282',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Gastrodiagnóstico',telefono:'809-221-4190',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Grupo Médico San Martín',telefono:'809-567-3271',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Hospital General Materno Infantil (Plaza de la Salud)',telefono:'809-565-7477',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Instituto de Cirugía Especializada',telefono:'809-688-3155',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Instituto de Maternidad San Rafael',telefono:'809-688-5511',plan:'Royal,Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Bonao',telefono:'809-525-3811',plan:'Royal,Max,Platinum',ubicacion:'Bonao')
Clinica.create(nombre:'CM Carolina de Jesús',telefono:'809-525-4404',plan:'Royal,Max,Platinum',ubicacion:'Bonao')
Clinica.create(nombre:'Clínica Nuestra Sra. de Lantigua',telefono:'809-525-3218',plan:'Royal,Max,Platinum',ubicacion:'Bonao')
Clinica.create(nombre:'Clínica San Antonio de Padua',telefono:'809-525-9446',plan:'Royal,Max,Platinum',ubicacion:'Bonao')
Clinica.create(nombre:'Instituto de Esp. Médicas Monseñor Nouel',telefono:'809-296-2002',plan:'Royal,Max,Platinum',ubicacion:'Bonao')
Clinica.create(nombre:'CM Cabrera',telefono:'809-589-7410',plan:'Royal,Max,Platinum',ubicacion:'Cabrera')
Clinica.create(nombre:'CM Dr. de la Cruz',telefono:'809-589-7566',plan:'Royal,Max,Platinum',ubicacion:'Cabrera')
Clinica.create(nombre:'Centro de Esp. Médicas Titi',telefono:'809-539-3345',plan:'Royal,Max,Platinum',ubicacion:'Constanza')
Clinica.create(nombre:'CM Núñez Hernández',telefono:'809-585-2901',plan:'Royal,Max,Platinum',ubicacion:'Cotui')
Clinica.create(nombre:'Clínica Dr. Paredes',telefono:'809-585-2265',plan:'Royal,Max,Platinum',ubicacion:'Cotui')
Clinica.create(nombre:'Clínica Nuestra Señora de las Mercedes',telefono:'809-585-2962',plan:'Royal,Max,Platinum',ubicacion:'Cotui')
Clinica.create(nombre:'Clínica Rosa Benita',telefono:'809-579-8266',plan:'Royal,Max,Platinum',ubicacion:'Dajabon')
Clinica.create(nombre:'Clínica Dr. Amaro Dra. Germosén',telefono:'809-587-2480',plan:'Royal,Max,Platinum',ubicacion:'Gaspar Hernandez')
Clinica.create(nombre:'CM Jarabacoa',telefono:'809-574-2247',plan:'Royal,Max,Platinum',ubicacion:'Jarabacoa')
Clinica.create(nombre:'Centro Obra social Salesiana',telefono:'809-574-2822',plan:'Royal,Max,Platinum',ubicacion:'Jarabacoa')
Clinica.create(nombre:'Centro de Esp. Médicas Vegano',telefono:'809-573-4849',plan:'Royal,Max,Platinum',ubicacion:'La Vega')
Clinica.create(nombre:'CM V Centenario',telefono:'809-573-4124',plan:'Royal,Max,Platinum',ubicacion:'La Vega')
Clinica.create(nombre:'CM Padre Fantino',telefono:'809-573-2533',plan:'Royal,Max,Platinum',ubicacion:'La Vega')
Clinica.create(nombre:'Policlínico La Vega',telefono:'809-573-9555',plan:'Royal,Max,Platinum',ubicacion:'La Vega')
Clinica.create(nombre:'CM Soto Toribio',telefono:'809-579-1898',plan:'Royal,Max,Platinum',ubicacion:'Las Matas de Santa Cruz')
Clinica.create(nombre:'CM Quirúrgico DR. Rafael Rodríguez',telefono:'809-572-6301',plan:'Royal,Max,Platinum',ubicacion:'Mao')
Clinica.create(nombre:'Clínica Perpetuo Socorro',telefono:'809-572-3210',plan:'Royal,Max,Platinum',ubicacion:'Mao')
Clinica.create(nombre:'Clínica San Judas Tadeo',telefono:'809-572-3588',plan:'Royal,Max,Platinum',ubicacion:'Mao')
Clinica.create(nombre:'Grupo Médico Mao',telefono:'809-572-6311',plan:'Royal,Max,Platinum',ubicacion:'Mao')
Clinica.create(nombre:'CM Guadalupe',telefono:'809-578-2216',plan:'Royal,Max,Platinum',ubicacion:'Moca')
Clinica.create(nombre:'Centro Materno Infantil y Esp. Dr. Victor Miguel Méndez',telefono:'809-578-5702',plan:'Royal,Max,Platinum',ubicacion:'Moca')
Clinica.create(nombre:'Inst. de Esp. Méd. Dr. José Gregorio Hernández',telefono:'809-578-6265',plan:'Royal,Max,Platinum',ubicacion:'Moca')
Clinica.create(nombre:'CM Gran Poder de Dios',telefono:'809-580-2311',plan:'Royal,Max,Platinum',ubicacion:'Moncion')
Clinica.create(nombre:'Clínica Dra. Suero',telefono:'809-579-2561',plan:'Royal,Max,Platinum',ubicacion:'Monte Cristi')
Clinica.create(nombre:'Centro de Esp. Médicas Dr. Pérez',telefono:'809-584-3057',plan:'Royal,Max,Platinum',ubicacion:'Nagua')
Clinica.create(nombre:'CM Dr. Constanzo',telefono:'809-552-4227',plan:'Royal,Max,Platinum',ubicacion:'El Seibo')
Clinica.create(nombre:'CM Esp. Dr. Ricardo Chahín',telefono:'809-552-2764',plan:'Royal,Max,Platinum',ubicacion:'El Seibo')
Clinica.create(nombre:'Grupo Médico Las Mercedes',telefono:'809-553-4010',plan:'Royal,Max,Platinum',ubicacion:'Hato Mayor')
Clinica.create(nombre:'CM Punta Cana',telefono:'809-552-1506',plan:'Royal,Max,Platinum',ubicacion:'Higuey')
Clinica.create(nombre:'Clínica Dr. Perozo',telefono:'809-554-2893',plan:'Royal,Max,Platinum',ubicacion:'Higuey')
Clinica.create(nombre:'Clínica Dr. Montás Ureña',telefono:'809-554-2379',plan:'Royal,Max,Platinum',ubicacion:'Higuey')
Clinica.create(nombre:'Clínica Dr. Virgilio Cedano',telefono:'809-554-3495',plan:'Royal,Max,Platinum',ubicacion:'Higuey')
Clinica.create(nombre:'Grupo Médico Higueyano',telefono:'809-554-2981',plan:'Royal,Max,Platinum',ubicacion:'Higuey')
Clinica.create(nombre:'CM Dr. Canela',telefono:'809-556-3135',plan:'Royal,Max,Platinum',ubicacion:'La Romana')
Clinica.create(nombre:'CM Dr. del Rosario',telefono:'809-556-3097',plan:'Royal,Max,Platinum',ubicacion:'La Romana')
Clinica.create(nombre:'CM Coral',telefono:'809-550-0097',plan:'Royal,Max,Platinum',ubicacion:'La Romana')
Clinica.create(nombre:'CM Oriental',telefono:'809-556-2555',plan:'Royal,Max,Platinum',ubicacion:'La Romana')
Clinica.create(nombre:'Centro de Esp. Médicas Romana',telefono:'809-550-4550',plan:'Royal,Max,Platinum',ubicacion:'La Romana')
Clinica.create(nombre:'CM Monte Plata',telefono:'809-551-6464',plan:'Royal,Max,Platinum',ubicacion:'Monte Plata')
Clinica.create(nombre:'Centro Hospitalario UCE',telefono:'809-529-6111',plan:'Royal,Max,Platinum',ubicacion:'San Pedro de Macoris')
Clinica.create(nombre:'CM de León',telefono:'809-529-5785',plan:'Royal,Max,Platinum',ubicacion:'San Pedro de Macoris')
Clinica.create(nombre:'CM Especializado Macorix',telefono:'809-529-8088',plan:'Royal,Max,Platinum',ubicacion:'San Pedro de Macoris')
Clinica.create(nombre:'Clínica de Medicina Familiar Dr. Franklin Peña',telefono:'809-526-7492',plan:'Royal,Max,Platinum',ubicacion:'San Pedro de Macoris')
Clinica.create(nombre:'Clínica del Niño',telefono:'809-529-3205',plan:'Royal,Max,Platinum',ubicacion:'San Pedro de Macoris')
Clinica.create(nombre:'Galmedical Internacional',telefono:'809-526-2044',plan:'Royal,Max,Platinum',ubicacion:'San Pedro de Macoris')
Clinica.create(nombre:'CM Popular Azuano',telefono:'809-521-1111',plan:'Royal,Max,Platinum',ubicacion:'Azua')
Clinica.create(nombre:'Semeda (CM DR. Pelletier)',telefono:'809-521-3447',plan:'Royal,Max,Platinum',ubicacion:'Azua')
Clinica.create(nombre:'CM Regional Dr. Aguasvivas',telefono:'809-522-3611',plan:'Royal,Max,Platinum',ubicacion:'Bani')
Clinica.create(nombre:'Grupo Médico Baní',telefono:'809-522-5005',plan:'Royal,Max,Platinum',ubicacion:'Bani')
Clinica.create(nombre:'CM Regional Magnolia',telefono:'809-524-2470',plan:'Royal,Max,Platinum',ubicacion:'Barahona')
Clinica.create(nombre:'Clínica Santo Tomás',telefono:'809-524-2349',plan:'Royal,Max,Platinum',ubicacion:'Barahona')
Clinica.create(nombre:'CM Dra. Cabrera',telefono:'809-527-0356',plan:'Royal,Max,Platinum',ubicacion:'Comendador')
Clinica.create(nombre:'CM Haina',telefono:'809-957-3972',plan:'Royal,Max,Platinum',ubicacion:'Haina')
Clinica.create(nombre:'Clínica Dr. Gómez Roa',telefono:'809-527-5332',plan:'Royal,Max,Platinum',ubicacion:'Las Matas de Farfán')
Clinica.create(nombre:'Clínica Dr. Díaz Vázquez',telefono:'809-527-3407',plan:'Royal,Max,Platinum',ubicacion:'Neyba')
Clinica.create(nombre:'Hospital Dr. Elio Fiallo',telefono:'809-524-0147',plan:'Royal,Max,Platinum',ubicacion:'Pedernales')
Clinica.create(nombre:'CM Constitución (CEMECO)',telefono:'809-288-3232',plan:'Royal,Max,Platinum',ubicacion:'San Cristobal')
Clinica.create(nombre:'CM Dr. Bethancourt & Asoc.',telefono:'809-528-2939',plan:'Royal,Max,Platinum',ubicacion:'San Cristobal')
Clinica.create(nombre:'Clínica San Cristóbal',telefono:'809-528-3463',plan:'Royal,Max,Platinum',ubicacion:'San Cristobal')
Clinica.create(nombre:'CM El Maniel',telefono:'809-558-2511',plan:'Royal,Max,Platinum',ubicacion:'San Jose de Ocoa')
Clinica.create(nombre:'Clínica Arias',telefono:'809-558-2233',plan:'Royal,Max,Platinum',ubicacion:'San Jose de Ocoa')
Clinica.create(nombre:'CM Anacaona',telefono:'809-557-2322',plan:'Royal,Max,Platinum',ubicacion:'San Juan de La Maguana')
Clinica.create(nombre:'Clínica Adames Michel',telefono:'809-527-5235',plan:'Royal,Max,Platinum',ubicacion:'San Juan de La Maguana')
Clinica.create(nombre:'Clínica Gómez Roa',telefono:'809-527-5332',plan:'Royal,Max,Platinum',ubicacion:'San Juan de La Maguana')
Clinica.create(nombre:'Igualas Médicas San Juan',telefono:'809-557-5345',plan:'Royal,Max,Platinum',ubicacion:'San Juan de La Maguana')

Clinica.create(nombre:"Centro de Diagnóstico y Medicina Avanzada Cedimat",telefono:"809-565-9989",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Centro de Medicina Avanzada Dr. Abel Gonzalez",telefono:"809-227-2235",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Centro de Obstetricia y Ginecología",telefono:"809-221-7100",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Centro de Otorrinolaringología y Especialidades",telefono:"809-682-0151",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Centro de Pediatría y Especialidades",telefono:"809-687-7618",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Centro de Salud de la Mujer Atabey",telefono:"809-412-8177",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Alcántara y González",telefono:"809-566-2121",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Antillano",telefono:"809-533-4715",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Corominas Pepín",telefono:"809-541-1400",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM del Caribe",telefono:"809-685-9403",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Dominicano",telefono:"809-531-2800",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Dominico - Cubano",telefono:"809-221-5501",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Dr. Betances",telefono:"809-476-7373",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Dr. Escaño",telefono:"809-687-2090",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Dr. Richardson Cruz",telefono:"809-567-1471",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Gazcue",telefono:"809-412-7851",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Herrera",telefono:"809-537-3770",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Hispánico",telefono:"809-596-0033",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Integral II",telefono:"809-788-6336",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Integral Santana Guzmán",telefono:"809-788-1003",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Juan Carlos",telefono:"809-699-1111",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Luperón",telefono:"809-684-3989",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Panamericano",telefono:"809-538-5281",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Real",telefono:"809-537-3940",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM Santos Aquino",telefono:"809-548-1002",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"CM UCE",telefono:"809-221-0171",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Centro Oriental de Ginecología y Obstetricia",telefono:"809-593-4386",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Centro Policlínico Nacional",telefono:"809-788-2323",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Centro Quirúrgico Esculapio",telefono:"809-682-6989",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Clínica Abreu",telefono:"809-688-4411",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Clínica Corazones Unidos",telefono:"809-567-4421",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Clínica Cruz Dorada",telefono:"809-689-5339",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Clínica Cruz Jiminian",telefono:"809-566-2271",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Clínica Dr. Abel González",telefono:"809-682-6001",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Clínica Dra. Evangelina Rodríguez (Pro-Familia II)",telefono:"809-684-3389",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Clínica Dr. Rosario",telefono:"809-681-3120",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Clínica Gómez Patiño",telefono:"809-685-9131",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Clínica Independencia",telefono:"809-533-2775",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Clínica Independencia Norte",telefono:"809-385-2787",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Clínica La Altagracia",telefono:"809-699-3494",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Clínica Rodríguez Santos",telefono:"809-333-6671",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Clínica Tamares Espinal",telefono:"809-379-2282",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Gastrodiagnóstico",telefono:"809-221-4190",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Grupo Médico San Martín",telefono:"809-567-3271",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Hospital General Materno Infantil (Plaza de la Salud)",telefono:"809-565-7477",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Instituto de Cirugía Especializada",telefono:"809-688-3155",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Instituto de Maternidad San Rafael",telefono:"809-688-5511",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Instituto Médico San Lucas",telefono:"809-688-8853",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Hospital General Regional Dr. Marcelino Velez Santana",telefono:"809-560-6666",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Centro de Esp. Médicas C & H",telefono:"809-523-5546",ubicacion:"Santo Domingo",plan:"Platinum")
Clinica.create(nombre:"Oftalmológica M&L",telefono:"809-620-1424",ubicacion:"Santo Domingo",plan:"Platinum")

Farmacia.create(nombre:"Farmax - SM Nacional",telefono:"809-333-4444",direccion:"27 de Febrero",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Berenice I",telefono:"809-592-0947",direccion:"Alma Rosa",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Carol",telefono:"809-565-2062",direccion:"Arroyo Hondo",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Medika",telefono:"809-549-4771",direccion:"Arroyo Hondo",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmax",telefono:"809-333-4444",direccion:"Arroyo Hondo",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmax - Delivery",telefono:"809-333-4444",direccion:"Arroyo Hondo",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Super Farmacia Melgen",telefono:"809-385-1000",direccion:"Arroyo Hondo",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Los Hidalgos",telefono:"809-616-7373",direccion:"Autopista Duarte",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmax Plaza Duarte",telefono:"809-333-4444",direccion:"Autopista Duarte",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Los Hidalgos",telefono:"809-621-2221",direccion:"Avenida Duarte",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Carol",telefono:"809-482-5440",direccion:"Bella Vista",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Churchill",telefono:"809-534-7032",direccion:"Bella Vista",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Los Hidalgos",telefono:"809-620-2420",direccion:"Bella Vista",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Doña Olga",telefono:"809-523-6498",direccion:"Boca Chica",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Carol",telefono:"809-594-3577",direccion:"Charles de Gaulle",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmax",telefono:"809-333-4444",direccion:"Charles de Gaulle",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmax - La Sirena",telefono:"809-333-4444",direccion:"Charles de Gaulle",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmax",telefono:"809-333-4444",direccion:"Charles Summers",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Santa Cruz",telefono:"809-688-1894",direccion:"Ciudad Nueva",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Macorix",telefono:"809-532-1226",direccion:"El Cacique",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Super Farmacia Popular",telefono:"809-566-6655",direccion:"El Millon",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Jerding",telefono:"809-563-7583",direccion:"El Millon",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Super Farmacia Melgen",telefono:"809-482-0000",direccion:"El Renacimiento",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Thasulij",telefono:"809-565-5112",direccion:"El Vergel",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Carol",telefono:"809-689-6000",direccion:"Gazcue",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmax",telefono:"809-333-4444",direccion:"Gazcue",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Pharma Delivery",telefono:"809-331-2000",direccion:"Gazcue",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Parroquial",telefono:"809-526-5924",direccion:"Guerra",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Carol",telefono:"809-472-4040",direccion:"Julieta",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Carol",telefono:"809-563-6060",direccion:"La Arboleda",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Carol - UCE",telefono:"809-685-3375",direccion:"La Esperilla",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Medika",telefono:"809-385-2788",direccion:"La Feria",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Carol",telefono:"809-541-6767",direccion:"Lope de Vega",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmax",telefono:"809-333-4444",direccion:"Lope de Vega",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmax - SM Nacional",telefono:"809-333-4444",direccion:"Lope de Vega",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmax - SM Pola",telefono:"809-333-4444",direccion:"Lope de Vega",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Santa María - Bravo",telefono:"809-482-4040",direccion:"Los Cacicazgos",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Los Hidalgos",telefono:"809-539-5602",direccion:"Luperon",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmax",telefono:"809-333-4444",direccion:"Megacentro",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Ana Luisa",telefono:"809-482-7037",direccion:"Mirador Norte",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Las Vegas",telefono:"809-534-4958",direccion:"Mirador Norte",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Santa María",telefono:"809-530-2272",direccion:"Mirador Norte",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Carol",telefono:"809-682-7080",direccion:"Maximo Gomez",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Los Hidalgos",telefono:"809-686-8604",direccion:"Miraflores",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Carol",telefono:"809-562-6767",direccion:"Naco",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Los Hidalgos",telefono:"809-541-4848",direccion:"Naco",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Madrid II",telefono:"809-562-2808",direccion:"Naco",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Paty",telefono:"809-562-6232",direccion:"Naco",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmax",telefono:"809-333-4444",direccion:"Nuñez de Caceres",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Fortuna II",telefono:"809-227-6616",direccion:"Paraiso",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Carol",telefono:"809-867-1002",direccion:"Piantini",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Los Hidalgos",telefono:"809-338-0700",direccion:"Piantini",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmax - La Sirena",telefono:"809-333-4444",direccion:"Piantini",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Pharmacropolis",telefono:"809-566-1174",direccion:"Piantini",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia San Rafael",telefono:"809-616-2013",direccion:"Piantini",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Madrid (Plaza Ince)",telefono:"809-544-4001",direccion:"Quisqueya",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Super Farmacia Mercedes Altagracia",telefono:"809-566-7825",direccion:"Quisqueya",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Super Farmacia Melgen",telefono:"809-381-1900",direccion:"Roberto Pastoriza",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmax - SM Pola",telefono:"809-333-4444",direccion:"Sarasota",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Santa María",telefono:"809-748-0088",direccion:"San Isidro",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Carol",telefono:"809-685-8024",direccion:"San Carlos",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Carol",telefono:"809-685-8165",direccion:"San Judas Tadeo",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Los Hidalgos",telefono:"809-592-4848",direccion:"San Isidro",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Los Hidalgos",telefono:"809-596-1297",direccion:"San Vicente",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Super Farmacia Melgen - Plaza Lama",telefono:"809-286-0050",direccion:"San Vicente",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Berenice II",telefono:"809-594-6583",direccion:"Villa Faro",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Rita",telefono:"809-688-4291",direccion:"Villa Faro",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Rita",telefono:"809-688-4291",direccion:"Villa Juana",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Carol - Sara I",telefono:"809-536-6363",direccion:"Villa Maria",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Buena Vista",telefono:"809-568-3323",direccion:"Villa Mella",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Faramcia Los Hidalgos",telefono:"809-741-0201",direccion:"Villa Mella",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Carol",telefono:"809-741-0044",direccion:"Villa Mella",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Los Hidalgos",telefono:"809-566-7703",direccion:"Winston Churchill",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Fortuna I",telefono:"809-682-7979",direccion:"Zona Universitaria",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia Milagro de la Caridad",telefono:"809-689-3630",direccion:"Zona Universitaria",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")
Farmacia.create(nombre:"Farmacia San Gerónimo",telefono:"809-687-0322",direccion:"Zona Universitaria",ubicacion:"Santo Domingo",plan:"Royal,Max,Platinum")