Clinica.create(nombre:'Centro de Obstetricia y Ginecología',telefono:'809-221-7100',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Centro de Otorrinolaringología y Especialidades',telefono:'809-682-0151',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Centro de Salud de la Mujer Atabey',telefono:'809-412-8177',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Alcántara y González',telefono:'809-566-2121',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Antillano',telefono:'809-533-4715',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Corominas Pepín',telefono:'809-541-1400',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM del Caribe',telefono:'809-685-9403',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Dominicano',telefono:'809-531-2800',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Dominico - Cubano',telefono:'809-221-5501',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Dr. Betances',telefono:'809-476-7373',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Dr. Escaño',telefono:'809-687-2090',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Dr. Richardson Cruz',telefono:'809-567-1471',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Gazcue',telefono:'809-412-7851',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Herrera',telefono:'809-537-3770',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Hispánico',telefono:'809-596-0033',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Integral II',telefono:'809-788-6336',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Integral Santana Guzmán',telefono:'809-788-1003',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Juan Carlos',telefono:'809-699-1111',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Luperón',telefono:'809-684-3989',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Panamericano',telefono:'809-538-5281',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Real',telefono:'809-537-3940',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Santos Aquino',telefono:'809-548-1002',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM UCE',telefono:'809-221-0171',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Centro Oriental de Ginecología y Obstetricia',telefono:'809-593-4386',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Centro Policlínico Nacional',telefono:'809-788-2323',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Centro Quirúrgico Esculapio',telefono:'809-682-6989',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Abreu',telefono:'809-688-4411',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Cruz Dorada',telefono:'809-689-5339',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Cruz Jiminian',telefono:'809-566-2271',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Dr. Abel González',telefono:'809-682-6001',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Dra. Evangelina Rodríguez (Pro-Familia II)',telefono:'809-684-3389',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Dr. Rosario',telefono:'809-681-3120',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Gómez Patiño',telefono:'809-685-9131',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Independencia',telefono:'809-533-2775',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Independencia Norte',telefono:'809-385-2787',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica La Altagracia',telefono:'809-699-3494',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Rodríguez Santos',telefono:'809-333-6671',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Clínica Tamares Espinal',telefono:'809-379-2282',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Gastrodiagnóstico',telefono:'809-221-4190',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Grupo Médico San Martín',telefono:'809-567-3271',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Hospital General Materno Infantil (Plaza de la Salud)',telefono:'809-565-7477',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Instituto de Cirugía Especializada',telefono:'809-688-3155',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'Instituto de Maternidad San Rafael',telefono:'809-688-5511',plan:'Max',ubicacion:'Santo Domingo')
Clinica.create(nombre:'CM Bonao',telefono:'809-525-3811',plan:'Max',ubicacion:'Bonao')
Clinica.create(nombre:'CM Carolina de Jesús',telefono:'809-525-4404',plan:'Max',ubicacion:'Bonao')
Clinica.create(nombre:'Clínica Nuestra Sra. de Lantigua',telefono:'809-525-3218',plan:'Max',ubicacion:'Bonao')
Clinica.create(nombre:'Clínica San Antonio de Padua',telefono:'809-525-9446',plan:'Max',ubicacion:'Bonao')
Clinica.create(nombre:'Instituto de Esp. Médicas Monseñor Nouel',telefono:'809-296-2002',plan:'Max',ubicacion:'Bonao')
Clinica.create(nombre:'CM Cabrera',telefono:'809-589-7410',plan:'Max',ubicacion:'Cabrera')
Clinica.create(nombre:'CM Dr. de la Cruz',telefono:'809-589-7566',plan:'Max',ubicacion:'Cabrera')
Clinica.create(nombre:'Centro de Esp. Médicas Titi',telefono:'809-539-3345',plan:'Max',ubicacion:'Constanza')
Clinica.create(nombre:'CM Núñez Hernández',telefono:'809-585-2901',plan:'Max',ubicacion:'Cotui')
Clinica.create(nombre:'Clínica Dr. Paredes',telefono:'809-585-2265',plan:'Max',ubicacion:'Cotui')
Clinica.create(nombre:'Clínica Nuestra Señora de las Mercedes',telefono:'809-585-2962',plan:'Max',ubicacion:'Cotui')
Clinica.create(nombre:'Clínica Rosa Benita',telefono:'809-579-8266',plan:'Max',ubicacion:'Dajabon')
Clinica.create(nombre:'Clínica Dr. Amaro Dra. Germosén',telefono:'809-587-2480',plan:'Max',ubicacion:'Gaspar Hernandez')
Clinica.create(nombre:'CM Jarabacoa',telefono:'809-574-2247',plan:'Max',ubicacion:'Jarabacoa')
Clinica.create(nombre:'Centro Obra social Salesiana',telefono:'809-574-2822',plan:'Max',ubicacion:'Jarabacoa')
Clinica.create(nombre:'Centro de Esp. Médicas Vegano',telefono:'809-573-4849',plan:'Max',ubicacion:'La Vega')
Clinica.create(nombre:'CM V Centenario',telefono:'809-573-4124',plan:'Max',ubicacion:'La Vega')
Clinica.create(nombre:'CM Padre Fantino',telefono:'809-573-2533',plan:'Max',ubicacion:'La Vega')
Clinica.create(nombre:'Policlínico La Vega',telefono:'809-573-9555',plan:'Max',ubicacion:'La Vega')
Clinica.create(nombre:'CM Soto Toribio',telefono:'809-579-1898',plan:'Max',ubicacion:'Las Matas de Santa Cruz')
Clinica.create(nombre:'CM Quirúrgico DR. Rafael Rodríguez',telefono:'809-572-6301',plan:'Max',ubicacion:'Mao')
Clinica.create(nombre:'Clínica Perpetuo Socorro',telefono:'809-572-3210',plan:'Max',ubicacion:'Mao')
Clinica.create(nombre:'Clínica San Judas Tadeo',telefono:'809-572-3588',plan:'Max',ubicacion:'Mao')
Clinica.create(nombre:'Grupo Médico Mao',telefono:'809-572-6311',plan:'Max',ubicacion:'Mao')
Clinica.create(nombre:'CM Guadalupe',telefono:'809-578-2216',plan:'Max',ubicacion:'Moca')
Clinica.create(nombre:'Centro Materno Infantil y Esp. Dr. Victor Miguel Méndez',telefono:'809-578-5702',plan:'Max',ubicacion:'Moca')
Clinica.create(nombre:'Inst. de Esp. Méd. Dr. José Gregorio Hernández',telefono:'809-578-6265',plan:'Max',ubicacion:'Moca')
Clinica.create(nombre:'CM Gran Poder de Dios',telefono:'809-580-2311',plan:'Max',ubicacion:'Moncion')
Clinica.create(nombre:'Clínica Dra. Suero',telefono:'809-579-2561',plan:'Max',ubicacion:'Monte Cristi')
Clinica.create(nombre:'Centro de Esp. Médicas Dr. Pérez',telefono:'809-584-3057',plan:'Max',ubicacion:'Nagua')
Clinica.create(nombre:'CM Dr. Constanzo',telefono:'809-552-4227',plan:'Max',ubicacion:'El Seibo')
Clinica.create(nombre:'CM Esp. Dr. Ricardo Chahín',telefono:'809-552-2764',plan:'Max',ubicacion:'El Seibo')
Clinica.create(nombre:'Grupo Médico Las Mercedes',telefono:'809-553-4010',plan:'Max',ubicacion:'Hato Mayor')
Clinica.create(nombre:'CM Punta Cana',telefono:'809-552-1506',plan:'Max',ubicacion:'Higuey')
Clinica.create(nombre:'Clínica Dr. Perozo',telefono:'809-554-2893',plan:'Max',ubicacion:'Higuey')
Clinica.create(nombre:'Clínica Dr. Montás Ureña',telefono:'809-554-2379',plan:'Max',ubicacion:'Higuey')
Clinica.create(nombre:'Clínica Dr. Virgilio Cedano',telefono:'809-554-3495',plan:'Max',ubicacion:'Higuey')
Clinica.create(nombre:'Grupo Médico Higueyano',telefono:'809-554-2981',plan:'Max',ubicacion:'Higuey')
Clinica.create(nombre:'CM Dr. Canela',telefono:'809-556-3135',plan:'Max',ubicacion:'La Romana')
Clinica.create(nombre:'CM Dr. del Rosario',telefono:'809-556-3097',plan:'Max',ubicacion:'La Romana')
Clinica.create(nombre:'CM Coral',telefono:'809-550-0097',plan:'Max',ubicacion:'La Romana')
Clinica.create(nombre:'CM Oriental',telefono:'809-556-2555',plan:'Max',ubicacion:'La Romana')
Clinica.create(nombre:'Centro de Esp. Médicas Romana',telefono:'809-550-4550',plan:'Max',ubicacion:'La Romana')
Clinica.create(nombre:'CM Monte Plata',telefono:'809-551-6464',plan:'Max',ubicacion:'Monte Plata')
Clinica.create(nombre:'Centro Hospitalario UCE',telefono:'809-529-6111',plan:'Max',ubicacion:'San Pedro de Macoris')
Clinica.create(nombre:'CM de León',telefono:'809-529-5785',plan:'Max',ubicacion:'San Pedro de Macoris')
Clinica.create(nombre:'CM Especializado Macorix',telefono:'809-529-8088',plan:'Max',ubicacion:'San Pedro de Macoris')
Clinica.create(nombre:'Clínica de Medicina Familiar Dr. Franklin Peña',telefono:'809-526-7492',plan:'Max',ubicacion:'San Pedro de Macoris')
Clinica.create(nombre:'Clínica del Niño',telefono:'809-529-3205',plan:'Max',ubicacion:'San Pedro de Macoris')
Clinica.create(nombre:'Galmedical Internacional',telefono:'809-526-2044',plan:'Max',ubicacion:'San Pedro de Macoris')
Clinica.create(nombre:'CM Popular Azuano',telefono:'809-521-1111',plan:'Max',ubicacion:'Azua')
Clinica.create(nombre:'Semeda (CM DR. Pelletier)',telefono:'809-521-3447',plan:'Max',ubicacion:'Azua')
Clinica.create(nombre:'CM Regional Dr. Aguasvivas',telefono:'809-522-3611',plan:'Max',ubicacion:'Bani')
Clinica.create(nombre:'Grupo Médico Baní',telefono:'809-522-5005',plan:'Max',ubicacion:'Bani')
Clinica.create(nombre:'CM Regional Magnolia',telefono:'809-524-2470',plan:'Max',ubicacion:'Barahona')
Clinica.create(nombre:'Clínica Santo Tomás',telefono:'809-524-2349',plan:'Max',ubicacion:'Barahona')
Clinica.create(nombre:'CM Dra. Cabrera',telefono:'809-527-0356',plan:'Max',ubicacion:'Comendador')
Clinica.create(nombre:'CM Haina',telefono:'809-957-3972',plan:'Max',ubicacion:'Haina')
Clinica.create(nombre:'Clínica Dr. Gómez Roa',telefono:'809-527-5332',plan:'Max',ubicacion:'Las Matas de Farfán')
Clinica.create(nombre:'Clínica Dr. Díaz Vázquez',telefono:'809-527-3407',plan:'Max',ubicacion:'Neyba')
Clinica.create(nombre:'Hospital Dr. Elio Fiallo',telefono:'809-524-0147',plan:'Max',ubicacion:'Pedernales')
Clinica.create(nombre:'CM Constitución (CEMECO)',telefono:'809-288-3232',plan:'Max',ubicacion:'San Cristobal')
Clinica.create(nombre:'CM Dr. Bethancourt & Asoc.',telefono:'809-528-2939',plan:'Max',ubicacion:'San Cristobal')
Clinica.create(nombre:'Clínica San Cristóbal',telefono:'809-528-3463',plan:'Max',ubicacion:'San Cristobal')
Clinica.create(nombre:'CM El Maniel',telefono:'809-558-2511',plan:'Max',ubicacion:'San Jose de Ocoa')
Clinica.create(nombre:'Clínica Arias',telefono:'809-558-2233',plan:'Max',ubicacion:'San Jose de Ocoa')
Clinica.create(nombre:'CM Anacaona',telefono:'809-557-2322',plan:'Max',ubicacion:'San Juan de La Maguana')
Clinica.create(nombre:'Clínica Adames Michel',telefono:'809-527-5235',plan:'Max',ubicacion:'San Juan de La Maguana')
Clinica.create(nombre:'Clínica Gómez Roa',telefono:'809-527-5332',plan:'Max',ubicacion:'San Juan de La Maguana')
Clinica.create(nombre:'Igualas Médicas San Juan',telefono:'809-557-5345',plan:'Max',ubicacion:'San Juan de La Maguana')



